#!/bin/sh
# script to generate launcher.pot from launcher.html
#   phrases to be translated must be on a single line
#   with single quotes, e.g. _('...')
# Author: Bert Freudenberg
PROJECTIDVERSION="Etoys Plugin Launcher"
IN="etoys-plugin-launcher.html"
OUT="etoys-plugin-launcher.pot"
DATE=`date -u "+%Y-%m-%d %H:%M-0000"`
# output header
(cat <<__EOF__
msgid "$BLA"
msgstr ""
"Project-Id-Version: $PROJECTIDVERSION\n"
"POT-Creation-Date: $DATE\n"
"PO-Revision-Date: $DATE\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=iso-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"
__EOF__
# extract _('...') labels, output as msgid/msgstr pairs
grep "_('" "$IN" \
| sed "s/\"/\\\\\"/g;s/.*_('/@msgid \"/;s/').*/\"@msgstr \"\"/" \
| tr '@' '\n' \
) > "$OUT"
