#!/usr/bin/python
# script to format lang.po files into javascript
#   the output needs to be pasted into launcher.html for each language
#   order of phrases must be the same in all languages 
# Author: Bert Freudenberg

import re, sys
from subprocess import Popen, PIPE

if len(sys.argv) < 2:
    print "USAGE: %s <lang>" % sys.argv[0]
    sys.exit(1)

language = sys.argv[1]

def output_js(lang, list):
    print "        translations['%s'] = [" % lang
    for l in list:
        print "            '%s'," % l.replace('\\"', '"')
    print "        ];"

# convert to iso-8859-1
po = Popen(['msgconv', '-t', 'UTF-8', language + '.po'], stdout=PIPE).communicate()[0]

# remove comment lines
po = re.sub('#.*\n', '', po)

msgids = []
msgstrs = []

for entry in re.split('msgid', po):
	if not entry:
		continue
	msgid,msgstr = re.split('msgstr', entry)
	# remove quotes, join lines
	msgid  = re.sub('\s*"(.*)"\s*(\n|$)', '\g<1>', msgid)
	msgstr = re.sub('\s*"(.*)"\s*(\n|$)', '\g<1>', msgstr)
	if not msgid:
		continue
	msgids.append(msgid)
	msgstrs.append(msgstr)

output_js('en', msgids)
output_js(language, msgstrs)
		



